### ISSUE TITLE
Integrate `latex2exp::TeX` into `add_pvalue`?

### ISSUE THREAD

**Issue by alesssia** [csdaw/ggprism#10]
Hi @csdaw,

I am using the `add_pvalue` function, and I am wondering whether it would be possible to have the P values nicely formatted as *P = 1x10<sup>-10</sup>* rather than *P=1e-10*. For doing this, I usually use `latex2exp::TeX` but I don't understand how to integrate it into the `add_pvalue` function. 

I am now using `rstatix` to both perform the statistical test and create the p-value table with the correct x and y position:

```
p <- ggplot(ToothGrowth, aes(x = factor(dose), y = len)) +
  geom_boxplot(aes(fill = dose), colour = "black") +
  theme_prism() +
  theme(legend.position = "none")
stat.test <- rstatix::t_test(ToothGrowth, len ~ dose, ref.group = "0.5") %>%
  rstatix::add_xy_position()
```
My first thought was to create a new field in `stat.test` to store the LaTeX expressions generated by `latex2exp::TeX`, as follows:

```
stat.test$p.latex <- latex2exp::TeX(stat.test$p.latex)
```
where `p.latex` Is a string vector containing LaTeX expressions (let's say `"1 \\times 10^{-10}"`) which I generated with another function. 
However, the `stats.test` object is not able to store expressions (as those outputted by ` latex2exp::TeX`). 

I then tried to modify the 

```
p + add_pvalue(stat.test, label = "p = {p.latex}")
```
bit and the `add_pvalue` function to have the expression printed, but I have no idea on how to do this. 

Would you be able to help me?
Many thanks in advance!

**Comment by csdaw** [comment]
Hi @alesssia ,

Thanks for the detailed issue, it really helps! 

As far as I know `add_pvalue` can't do this, but it should be simple to add. I can give it a `parse` argument like in `ggplot2::geom_text` which will be able to parse a plotmath expression.

See this simple example below using `geom_text`:

``` r
library(magrittr)
library(ggplot2)
library(ggprism)
# also use rstatix

p <- ggplot(ToothGrowth, aes(x = factor(dose), y = len)) + 
  geom_boxplot(aes(fill = dose), colour = "black") + 
  theme_prism() + 
  theme(legend.position = "none")

stat.test <- rstatix::t_test(ToothGrowth, len ~ dose, ref.group = "0.5") %>% 
  rstatix::add_xy_position()

## add a character column to stat.test with the plotmath expression 
## you want to use
stat.test$p.exprs <- paste0("P==1*x*10^", round(log10(stat.test$p.adj), 0))

## or use this rather ugly expression if you want everything italicised
# stat.test$p.exprs <- lapply(
#   paste(round(log10(stat.test$p.adj), 0)), 
#   function(x) bquote(italic("P = 1x10"^.(x)))
# )

p + geom_text(aes(label = p.exprs, x = xmax, y = y.position), 
              data = stat.test, parse = TRUE)
```

![](https://i.imgur.com/iNaTcLL.png)

<sup>Created on 2021-06-15 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by csdaw** [comment]
Hi @alesssia,

I've updated `add_pvalue()` to have a `parse` argument like `geom_text()`. You can install the Github version of `ggprism` to try it out.

Sorry I'm unfamiliar with `latex2exp` but from what I can tell it generates plotmath expression which I am a bit more familiar with. Now you can add a column to the p-value table with plotmath expressions to use to make prettier labels.

See an example below:

``` r
library(magrittr)
library(ggplot2)
library(ggprism)
# also use rstatix

p <- ggplot(ToothGrowth, aes(x = factor(dose), y = len)) + 
  geom_boxplot(aes(fill = dose), colour = "black") + 
  theme_prism() + 
  theme(legend.position = "none")

stat.test <- rstatix::t_test(ToothGrowth, len ~ dose, ref.group = "0.5") %>% 
  rstatix::add_xy_position()

stat.test$p.exprs <- paste0("P==1*x*10^", round(log10(stat.test$p.adj), 0))

p + add_pvalue(stat.test, label = "p.exprs", parse = TRUE)
```

![](https://i.imgur.com/h1mCzpt.png)

<sup>Created on 2021-06-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by alesssia** [comment]
Hi @csdaw,
this is brilliant, thank you so much!
