### ISSUE TITLE
Unable to display legend title

### ISSUE THREAD

**Issue by Hongxy09** [csdaw/ggprism#23]
I tried to add the legend title to my data, but I found that if I added theme_prism(base_size = 14) my legend title would disappear, if I commented this out the legend title would appear again, I don't know what is wrong, can someone help me?
I used R4.1.3 and downloaded prism version 1.0.2

**Comment by csdaw** [comment]
`theme_prism()` hides the legend title by default but you can simply add it back. Hope this helps.

``` r
library(ggplot2)
library(ggprism)

data("ToothGrowth")

ggplot(ToothGrowth, aes(x = supp, y = len, fill = supp)) + 
  geom_boxplot() +
  theme_prism()
```

![](https://i.imgur.com/WRCkmUU.png)

``` r

ggplot(ToothGrowth, aes(x = supp, y = len, fill = supp)) + 
  geom_boxplot() +
  theme_prism() + 
  theme(legend.title = element_text())
```

![](https://i.imgur.com/lciSULz.png)

<sup>Created on 2022-11-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Hongxy09** [comment]
This solved my problem! Thank you very much!



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Charlotte ***@***.***> |
| Date | 11/17/2022 18:33 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [csdaw/ggprism] Unable to display legend title (Issue #23) |

theme_prism() hides the legend title by default but you can simply add it back. Hope this helps.

library(ggplot2)
library(ggprism)

data("ToothGrowth")

ggplot(ToothGrowth, aes(x=supp, y=len, fill=supp)) + 
  geom_boxplot() +
  theme_prism()

ggplot(ToothGrowth, aes(x=supp, y=len, fill=supp)) + 
  geom_boxplot() +
  theme_prism() + 
  theme(legend.title= element_text())

Created on 2022-11-17 with reprex v2.0.2
