### ISSUE TITLE
The `legend.text.align` theme element is not defined in the element hierarchy.

### ISSUE THREAD

**Issue by myominnoo** [csdaw/ggprism#26]
Hi, 
I've got this error when I updated the ggplot2 to the latest version 3.4.4.9000. `The `legend.text.align` theme element is not defined in the element hierarchy.`

I think it has something to do with ggplot2 deprecating the `legend.text.align` argument of `theme()`.  

Thanks!

**Comment by samuel-marsh** [comment]
Hi,

Yes, also ran into similar issue.  There is a PR from ggplot2 team that should hopefully resolve errors.  See #25.

Best,
Sam

**Comment by Dr-hejie** [comment]
I tried and indeed found that the issue is caused by an incompatibility between the versions of ggplot2 and ggprism. I observed that the problem does not occur when using the following version combination:

> packageVersion("ggprism")
[1] ‘1.0.4’
> packageVersion("ggplot2")
[1] ‘3.4.4’

**Comment by csdaw** [comment]
This has been resolved in the latest ggprism CRAN version 1.0.5.

**Comment by teunbrand** [comment]
Thank you for getting this package to work again!

**Comment by csdaw** [comment]
And thanks for all your work helping package maintainers fix their packages!
