### ISSUE TITLE
adding new themes

### ISSUE THREAD

**Issue by kengcher** [csdaw/ggprism#3]
Hi!

i chanced upon your package and was wondering how i can add new themes to it?

Thank you very much and look forward to hearing back from you.

**Comment by csdaw** [comment]
Hi there, 

I'm happy you stumbled across my package (though its not quite finished/documented yet as you can see...).

The easiest way to add a theme would be to just define your own theme function that builds upon `theme_prism()`. See the [ggplot2 book](https://ggplot2-book.org/extensions.html) or [this blog post](https://www.r-bloggers.com/2018/09/custom-themes-in-ggplot2/) for more details.

Here is how I would do it (let me know if this helps):

``` r
library(ggplot2)
library(ggprism)

theme_new <- function(base_size = 14,
                      base_family = "sans",
                      base_fontface = "plain",
                      base_line_size = base_size / 14,
                      base_rect_size = base_size / 14,
                      axis_text_angle = 0,
                      border = FALSE) {
  theme_prism(palette = "black_and_white",
              base_size = base_size,
              base_family = base_family,
              base_fontface = base_fontface,
              base_line_size = base_line_size,
              base_rect_size = base_rect_size,
              axis_text_angle = axis_text_angle,
              border = border) %+replace% 
    theme(panel.background = element_rect(fill = "pink",
                                          colour = NA),
          axis.text = element_text(colour = "red"),
          axis.title = element_text(face = "bold", colour = "orange"))
}

p <- ggplot(mtcars, aes(x = disp, y = mpg)) + 
  geom_point()

p + theme_prism() + labs(title = "theme_prism()")
```

![](https://i.imgur.com/89jSml1.png)

``` r
p + theme_new() + labs(title = "theme_new()")
```

![](https://i.imgur.com/dah0wuj.png)

<sup>Created on 2020-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
